name: one_unit_every_day
description: "OneUnitEveryDay - Complete one unit of work per day per activity."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
